pipeline {
    agent any

    environment {
        APPLICATION_DIR = "/var/www/html/nox_scheduler_api"
        DEPLOY_DIR = "/var/www/html/nox_scheduler_api_deploy"
        BRANCH = "master"
    }

    stages {
        stage('Verificar Mudanças') {
            steps {
                script {
                    def changes = sh(script: 'git diff --name-only HEAD~1 HEAD', returnStdout: true).trim()
                    if (!changes.contains("api/")) {
                        echo "Nenhuma mudança na pasta api/. Pulando deploy."
                        currentBuild.result = 'ABORTED'
                        return
                    }
                }
            }
        }

        stage('Clone do Código') {
            steps {
                sh "mkdir -p ${DEPLOY_DIR}"

                dir("${DEPLOY_DIR}") {
                    git branch: "${BRANCH}", credentialsId: 'github', url: 'git@github.com:lucaskaiut/nox-schduler.git'
                    sh 'git pull origin master'
                }
            }
        }

        stage('Copia .env') {
            steps {
                dir("${DEPLOY_DIR}/api") {
                    sh 'cp .env.prod .env'
                }
            }
        }

        stage('Instalar Dependências') {
            steps {
                dir("${DEPLOY_DIR}/api") {
                    sh 'composer install --no-interaction --prefer-dist --optimize-autoloader'
                }
            }
        }

        stage('Copiar arquivos') {
            steps {
                sh """
                    sudo rsync -av --no-group --exclude='storage' ${DEPLOY_DIR}/api/ ${APPLICATION_DIR}/
                    
                    rm -rf ${DEPLOY_DIR}                    
                """
            }
        }


        stage('Configurar Permissões') {
            steps {
                script {
                    def commands = """
                        chown -R www-data:www-data ${APPLICATION_DIR}
                        find ${APPLICATION_DIR} -type f -exec chmod 644 {} \\;
                        find ${APPLICATION_DIR} -type d -exec chmod 755 {} \\;
                    """
                    sh commands
                }
            }
        }

        stage('Rodar Migrations') {
            steps {
                dir("${APPLICATION_DIR}") {
                    sh 'php artisan migrate --force'
                }
            }
        }
    }

    post {
        success {
            echo 'Deploy da API realizado com sucesso!'
        }
        failure {
            echo 'Falha no deploy da API. Verifique os logs para mais detalhes.'
        }
        aborted {
            echo 'Deploy da API abortado. Nenhuma mudança relevante na pasta api/.'
        }
    }
}